### ISSUE TITLE
(Request)

### ISSUE THREAD

**Issue by Doogan2** [IAmClassical/CityRP-EvoRP-#1]
This is more of a request then anything. 1: New to github 2: I need your help

Alright so i have been trying to find this gamemode everywhere. i understand that the original is called "Applejack"  Now i have somewhat experience with coding and all that jazz. but i do not understand how to install this or even get it to work. the closest i get is the loading screen. i have done all the mysql stuff and setup the data base requirements but i get a lot of errors. i really don't understand how it all works (Witch is my problem and i should stop) i would really, really like to get this gamemode working. i bought a vps the other day and have a darkrp server but as we all know "DarkRP" is crap and i wish to start an uprising for these types of servers to be great again.

Please help with a full tutorial or description  on how to make it all work.

Thank you

**Comment by IAmClassical** [comment]
Yeah, the mysql side of things are a issue. There are some nice people trying to help me fix this aspect of the gamemode. I will leave any updates I make on here/the facepuch post. If you would like to work with me, just message me on steam. You can find my steam on facepuch.
Here is the facepuch post I made regarding this gamemode: https://facepunch.com/showthread.php?t=1520107
